services:
  php:
    image: nayleen/php:${PHP_VERSION:-8.3}
    container_name: async_php
    depends_on:
      redis:
        condition: service_started
    environment:
      PHP_CS_FIXER_IGNORE_ENV: ${PHP_CS_FIXER_IGNORE_ENV:-0}
      PHP_INI_TEMPLATE_FILE: development
      REVOLT_DRIVER: ${REVOLT_DRIVER:-Revolt\EventLoop\Driver\StreamSelectDriver}
      XDEBUG_MODE: ${XDEBUG_MODE:-off}
    init: true
    networks:
      - async
    restart: "no"
    tmpfs:
      - /tmp
    volumes:
      - ./:/app/src

  redis:
    image: redis:7-alpine
    container_name: async_redis
    networks:
      - async
    restart: "no"

networks:
  async:
    driver: bridge
    name: async
