services:
  php:
    image: thecodingmachine/php:8.1-v4-cli
    container_name: php
    environment:
      - PHP_EXTENSION_MSGPACK=1
      - PHP_EXTENSION_XDEBUG=1
      - XDEBUG_MODE=off
    init: true
    networks:
      - async
    restart: "no"
    volumes:
      - ./:/usr/src/app

  redis:
    image: redis:7-alpine
    container_name: redis
    networks:
      - async
    restart: "no"

networks:
  async:
    driver: bridge
    name: async
