services:
  php:
    image: thecodingmachine/php:8.1-v4-cli
    container_name: php
    depends_on:
      redis:
        condition: service_started
    environment:
      - PHP_EXTENSION_APCU=1
      - PHP_EXTENSION_XDEBUG=1
      - PHP_INI_APC__ENABLE_CLI=1
      - XDEBUG_MODE=debug
    init: true
    networks:
      - async
    restart: "no"
    volumes:
      - ./:/usr/src/app

  redis:
    image: redis:7-alpine
    container_name: redis
    networks:
      - async
    restart: "no"

networks:
  async:
    driver: bridge
    name: async
