version: "3.7"

services:
    php:
        image: thecodingmachine/php:8.1-v4-cli
        container_name: php
        environment:
            - PHP_EXTENSION_XDEBUG=1
        init: true
        links:
            - redis
        networks:
            - async-runtimes
        restart: "no"
        volumes:
            - ./:/usr/src/app

    redis:
        image: redis:7-alpine
        container_name: redis
        networks:
            - async-runtimes
        restart: "no"

networks:
    async-runtimes:
        driver: bridge
        name: async-runtimes
