name: ci

on:
  pull_request_target:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - 8.3
        dependencies:
          - stable
          - lowest
    env:
      PHP_VERSION: ${{ matrix.php }}
      DEPENDENCY_VERSIONS: ${{ matrix.dependencies }}
    steps:
      - uses: actions/checkout@v4
      - run: docker-compose pull --quiet
      - run: make ci
