name: ci

on:
  pull_request_target:
    branches:
      - main
  push:
    branches:
      - main

env:
  XDEBUG_MODE: off

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - 8.3
          - 8.4
        dependencies:
          - stable
          - lowest
        loop_driver:
          - StreamSelectDriver
          - EvDriver
          - EventDriver
          - UvDriver
    env:
      DEPENDENCY_VERSIONS: ${{ matrix.dependencies }}
      PHP_VERSION: ${{ matrix.php }}
      REVOLT_DRIVER: "Revolt\\EventLoop\\Driver\\${{ matrix.loop_driver }}"
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: docker compose pull --quiet
      - run: task ci
